# Generated by Django 4.0.4 on 2022-05-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('upvotes', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1024)),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
